# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d295fac66b0349b81819e7a05209a009f5ae541230b22585ad1bba51a35b0ba1dd5c2108bbf6a6a18cbb96508623f57948cc73340af504f4d1dca3480b0bfde0

test:
  secret_key_base: fa84781be59c93ad0c7e2430dbee4ea88da3e2eefb1b26865b74faf8f70188ee6ac3809d21df41797153b71a514a8857c496c8a9f76a0a2331228a863dc011c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
